apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsoft-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsoft-a
  template:
    metadata:
      labels:
        app: microsoft-a
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: microsoft-a
        image: zivse/microsoft-homework-a:latest
        livenessProbe:
          exec:
            command:
              - cat
              - /app/main.py
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 8080
          name: microsoft-a
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 1000m
            memory: 100Mi